import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {storyblokInit, apiPlugin} from "@storyblok/react/rsc";
import { StoryblokProvider } from "./components/StoryblokProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cachedFetch = (input: any, init?: any): Promise<Response> =>{
  return fetch(input, {
    ...init,
    cache: "no-store",
  })
}

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  apiOptions: {
    fetch: cachedFetch,
  }
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <div>Layout Z</div>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}
